### ISSUE TITLE
Ability to use  XDG_CONFIG_HOME path for ZK's config and templates

### ISSUE THREAD

**Issue by megalithic** [mickael-menu/zk#10]
Hey there @mickael-menu!

I was recently alerted to this project by @evantravers and am super excited to dive in!

One thing I've been trying to do with my dotfiles and my system setup in general, is to move everything config-wise to `XDG_CONFIG_HOME` (`~/.config/`). I see there looks to be some flexibility for `path` in `zk.go` where you're joining that given `path` with a fixed `.zk` dir for those config items. I'm a little bit confused on what the `.zk/` path is relative to. 

Any thoughts around this as an option?

Thanks again for such a wonderful tool!

**Comment by mickael-menu** [comment]
Hi Seth, welcome!

`zk` is working a bit like Git, in that its config is local to a particular notebook. The `.zk` folder is located at the root directory of a notebook. [You can find more info about it  here](https://github.com/mickael-menu/zk/blob/main/docs/notebook.md).

But I think some of `zk`'s settings would definitely make sense in a global config, such as [command aliases](https://github.com/mickael-menu/zk/blob/main/docs/config-alias.md) and templates. `XDG_CONFIG_HOME` seems a perfect fit for this! I think this could be implemented by reading the global config, then merging the local one when opening the current notebook.

**Comment by megalithic** [comment]
Ahh, that makes more sense. I was trying to get a sense of how/what was acting as the root "key" for the config and the notebooks. 

I'm curious, do you use something separate for more "wiki"/vimwiki types of use cases?

**Comment by mickael-menu** [comment]
I spawned a new discussion for Vim: https://github.com/mickael-menu/zk/discussions/11

> Ever considered doing a live-stream or a youtube video showing some of your real-world usages? 🙏

No but why not! I don't think my setup is very special, but it could help showcase some of `zk`'s coolest features better than the animated SVGs in [Getting started](https://github.com/mickael-menu/zk/blob/main/docs/getting-started.md).

**Comment by evantravers** [comment]
I'm going to 👍 this idea… mostly because I sync my wiki back and forth on dropbox… and I can't figure out how to tell the second computer to use ~/Dropbox/wiki as it's primary notebook. On the first computer, I just ran `zk init`, and everything was fine, but I can't figure out how to point `zk` at the folder on the second… I think a config file would be good.

**Comment by mickael-menu** [comment]
@evantravers I started working on the global config, but I'm not sure this is going to solve your problem.

A `zk` notebook is really like a Git repository, and `zk init` is similar to `git init`: it creates a `.zk` folder in the current directory. As long as the `.zk` folder is also synchronized with Dropbox, you should not need to run `zk init` on the other computer.

There is no notion of "global notebook" with `zk`, the current directory needs to be inside a notebook directory to run `zk` commands.

I can understand the appeal of running `zk` commands from anywhere with a global notebook, but I'm afraid this would make it more complicated to work with several notebooks.

**Comment by mickael-menu** [comment]
I implemented it in this PR: https://github.com/mickael-menu/zk/pull/12

[Here's a macOS build](https://github.com/mickael-menu/zk/files/6152231/zk.zip), I will wait for your feedback before merging the PR. And I'm looking forward to any cool aliases you may add to your dotfiles repos! ;)

**Comment by mickael-menu** [comment]
@evantravers @megalithic I've given more thought to the global notebook issue and came up with this potential solution: https://github.com/mickael-menu/zk/issues/13

**Comment by megalithic** [comment]
Your solution from #13 makes complete sense and seems like the direction to go.

**Comment by evantravers** [comment]
I love this. I honestly think that this “git-like” approach is a perfect fit for both vim and unix-y atomic notes in general. Very excited to follow along.

**Comment by mickael-menu** [comment]
[Here's an updated macOS build](https://github.com/mickael-menu/zk/files/6166575/zk.zip) supporting the `ZK_NOTEBOOK_DIR` env variable per #14. Thanks again for your feedback, I think it's making `zk` more enjoyable to use!

**Comment by evantravers** [comment]
I pulled and updated it today to play with it… this is really fun. Thanks Mickaël!

**Comment by megalithic** [comment]
@mickael-menu quick question around global config/templates (https://github.com/mickael-menu/zk/blob/main/docs/config.md#global-configuration-file)..

there still seems to be a requirement that a config.toml exist in your notebook's directory (even the notebook defined in the ZK_NOTEBOOK_DIR; is this expected behaviour?

thanks!

**Comment by mickael-menu** [comment]
Not really, it's probably just a leftover from the previous behavior. I guess checking the presence of the `.zk` marker should be enough. Thanks for spotting that 👍
