### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by ubuntupunk** [mickael-menu/zk#101]
I get this on Ubuntu 20.04
```
zk: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
```
I have lib 66 on my system
```
/usr/lib/i386-linux-gnu/libicuuc.so.66
/usr/lib/i386-linux-gnu/libicuuc.so.66.1
/usr/lib/x86_64-linux-gnu/libicuuc.a
/usr/lib/x86_64-linux-gnu/libicuuc.so
/usr/lib/x86_64-linux-gnu/libicuuc.so.66
/libicuuc.so.66.1
```

**Comment by mickael-menu** [comment]
`zk` is built with dynamic linking (because of some dependencies it's complicated to link it statically).

If you don't have the expected library, I suggest you build `zk` yourself [following these instructions](https://github.com/mickael-menu/zk#build-from-scratch).
