### ISSUE TITLE
Date helper fails: no value can start with %

### ISSUE THREAD

**Issue by j-steinbach** [mickael-menu/zk#102]
I am trying to format my weekly-journal filenames with [strftime-style placeholders](https://github.com/mickael-menu/zk/blob/main/docs/template.md#date-helper), as described in the documentation.

Below is my config. The commented string is what I want to do (`2021-W45-Friday-12-November`), the other one is copied directly from the docs. Both fail with `zk: error: failed to open notebook: failed to read config: 89, 25): parsing error: no value can start with % `

```
[group."journal/weekly".note]
template = "journal.weekly.md"
#filename = "{{date now "%y-W%V-%A-%d-%B"}}"
filename = "{{date now "%m-%d-%Y"}}"
```

**Comment by mickael-menu** [comment]
It might be because you are nesting double-quotes, try with:

```
filename = "{{date now '%m-%d-%Y'}}"
```

**Comment by j-steinbach** [comment]
Yes, this fixed it! 

---

I think this could be added to the docs? Maybe in the "config-group" file or as a "common-errors" file? On the other hand people will probably just google and find this issue.

**Comment by mickael-menu** [comment]
Well I hope this issue will answer future questions ;) In the doc I used single quotes in the examples.
