### ISSUE TITLE
Feature request: Don't directly create a note with `zk edit` and leave it to the `$EDITOR`

### ISSUE THREAD

**Issue by ghost** [mickael-menu/zk#107]
For example, if you set `editor=vim` for example and put `:q` (don't save that), zk saves the file. Also tested with  mousepad.

**Comment by mickael-menu** [comment]
This is expected, `zk edit` creates a new note on the file system, *then* open it with your editor.

If you just want to see how a note would look like without really creating it, you can use `zk new --dry-run`.

**Comment by somenxavier** [comment]
But you can change your mind: I start a note, but I have to go (in a hurry), so you don't want to save that. This is my case more times. Perhaps zk could save file after edit is completed (and `$EDITOR` saves effectively the file - so no `:q` in vim).

**Comment by mickael-menu** [comment]
That could make sense, I'll think about it.

**Comment by kabouzeid** [comment]
If someone else comes across this issue, I‘m using `:Delete` from tpope‘s https://github.com/tpope/vim-eunuch instead of `:q` for this exact use case.

I don‘t really think it‘s possible for zk to solve this while staying editor agnostic. You can probably close this 🤷🏽‍♂️

**Comment by mickael-menu** [comment]
Good point, I'm not sure it's possible.

Personally I added this in my nvim config:

```viml
nmap ZX :!rm %:p<CR>ZZ
```
