### ISSUE TITLE
LSP go to definition goes to incorrect note

### ISSUE THREAD

**Issue by pwntester** [mickael-menu/zk#111]
Hi,

I group notes for the same project under a directory called `<DATE> - Project name` and then I have a main note for that project on that directory with the same name `<DATE> - Project name.md`. When I add a link to that note (`[[<DATE> - Project name]]`) and use the LSP go to definition feature, it opens another note from the same directory.

Steps to reproduce:
- Create a directory called `2021-12-31 - test`
- Create a note called `2021-12-31 - test.md` in `2021-12-31 - test`
-  Create a note called `another note.md` in `2021-12-31 - test`
-  In a different note add the following link (`[[2021-12-31 - test]]`) 
-  Use LSP go to definition to navigate to the note. In my case `another note.md` is opened instead.

Thanks

**Comment by mickael-menu** [comment]
This is caused by `zk` matching any note containing the given portion in its path, ordered by the smallest path.

I guess it could be changed to give precedence to the filename instead of the whole path.

**Comment by pwntester** [comment]
that would be great!

**Comment by mickael-menu** [comment]
@pwntester Could you check out the latest `main` and see if it fixes the problem for you?

**Comment by pwntester** [comment]
Seems to works flawlessly! Will test more thoughfully during the next days. Thanks!!
