### ISSUE TITLE
 Modern arch based systems support

### ISSUE THREAD

**Issue by VolkovIlia** [mickael-menu/zk#113]
Since I've updated my system, can't use and build zk anymore. I've got error:
`zk: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory`
The modern core package is  `icu 70.1-1`  Can you make some updates for supporting it? [libicuio.so](https://archlinux.org/packages/core/x86_64/icu/)

**Comment by VolkovIlia** [comment]
Sorry, this issue is not about "supporting arch", mb it's about build issue from aur. So you are not maintainer of aur repo. I will close this issue.

**Comment by mickael-menu** [comment]
Yes, maybe check out with @nogweii directly? See https://github.com/mickael-menu/zk/discussions/45

**Comment by daylinmorgan** [comment]
@VolkovIlia I had a similar issue using the prebuilt linux binary on the releases page on my system.

`zk: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory`

I was able to get around this by compiling the needed object from the AUR. In my case [icu63](https://aur.archlinux.org/packages/icu63/).
