### ISSUE TITLE
'zk init' terminated by signal SIGTERM (Polite quit request)

### ISSUE THREAD

**Issue by j-steinbach** [mickael-menu/zk#118]
My tried-and-tested ZK install doesn't work anymore. No matter which command I give, my RAM + SWAP go to 100% (~32GB combined), my computer freezes, and then the command quits. 

This only happens in my "real" ZK folder. I created a new empty folder in `/tmp/test` and ran `zk init` there -- it worked.

This happens to me on both v0.7.0 and 0.8.0. I removed my `.zk` directory and tried re-creating it, but to no avail.

The first time this bug happened was when I ran a `zk new` command whilst playing/idling the [paperclip game](https://www.decisionproblem.com/paperclips/). My PC was already on heavy load/dying, and the zk command just died. Afterwards, even after restarting, zk just stopped working. So maybe this has to do with memory.

**Comment by mickael-menu** [comment]
There might be an issue during the indexing phase. Could you try running this in your notebook and see if you can identify the culprit note?

```sh
mkdir .zk
zk index --verbose
```

Making an empty `.zk` is enough to let `zk` recognize a directory as a notebook.

**Comment by j-steinbach** [comment]
Is `--verbose` a valid flag?

```
 ↳ zk index --verbose
zk: error: unknown flag --verbose
```

**Comment by mickael-menu** [comment]
Yes since `0.8.0`, you should see it in `zk index -h`

**Comment by j-steinbach** [comment]
Maybe I am blind, but I don't see it:

![image](https://user-images.githubusercontent.com/69524139/145880964-06516ac9-0c98-4bd5-b044-fdb9e96d9f9d.png)

**Comment by mickael-menu** [comment]
That's weird... Where did you get your `zk` binary?

**Comment by j-steinbach** [comment]
I built it myself (NixOS), from `commit =  "9ae8e5b041fc26a1e5aba03bc899b7cd7037c5d2"; shortcommit = "9ae8e5b";`. Still, my build might be faulty, so I am going to re-check that.

But the problem has been happening with the old 0.7.0 as well, which I built weeks ago. And that one had been working until yesterday.

**Comment by mickael-menu** [comment]
Thanks, I'll take a look into this one!

**Comment by j-steinbach** [comment]
Np, thank you creating this tool and for taking the time and going through this with me. :)
