### ISSUE TITLE
--no-input doesn't seem to work for `zk init`

### ISSUE THREAD

**Issue by mhanberg** [mickael-menu/zk#121]
If I do `zk init --no-input`, it still prompts me for the link style and tag style.

It would be nice to have defaults for those so the flag would work so that I can create the "test automation` part of my [homebrew-tap](https://github.com/mhanberg/homebrew-zk), which is required to get the formula submitted to the core repository.

ideally the test would be something like 

```sh
zk init --no-input
echo "some note" > someid.md
zk index
zk list

# some assertion that it listed the note
```

**Comment by mickael-menu** [comment]
You're right, it was an oversight when adding the `init` wizard.

**Comment by mhanberg** [comment]
awesome, thanks!
