### ISSUE TITLE
Run commands from outside a notebook directory

### ISSUE THREAD

**Issue by mickael-menu** [mickael-menu/zk#13]
[There has been some discussions](https://github.com/mickael-menu/zk/issues/10) around the best way to manage a global notebook.

Declaring in the global configuration file a default notebook would go against the design of `zk` in my opinion. A notebook is like a Git repository, with a `.zk` marker similar to `.git`.

However, it could be interesting to specify from the command line the notebook where `zk` commands are run. There is a precedent with Git, which provides [`--git-dir`](https://git-scm.com/docs/git#Documentation/git.txt---git-dirltpathgt) and [`--work-tree`](https://git-scm.com/docs/git#Documentation/git.txt---work-treeltpathgt).

I suggest specifying the path to the notebook with (in order of precedence):

* `--notebook-dir <path>`
* current working directory (or its parents)
* `ZK_NOTEBOOK_DIR` env variable

To simplify, any relative path provided as arguments would be relative to the notebook directory (when set explicitly), which allows stuff like:

```sh
$ zk list --exclude journal --notebook-dir ~/notes
```

In practice, that means that someone using a single notebook can set it as a "default global one" with `ZK_NOTEBOOK_DIR` in `~/.profile`.

**Comment by megalithic** [comment]
Exactly this!
