### ISSUE TITLE
How does zk saerches for tags and how to use tags correctly ?

### ISSUE THREAD

**Issue by rafamadriz** [mickael-menu/zk#132]
Hey, thanks for this tool, I've been playing with it and I really like it.

Something that it's not clear to me is how does `zk` searches for tags and how to use them. I have selected the `#hashtag`  method, and the only way I can make `zk` to list tags is by putting them in the metadata header with the YAML frontmatter. Like this:

```md
---
tags: cameras testing goo
---
```

That's the only way that tags get listed when doing `zk tag list` or `zk list -t cameras`. But if I use the hashtag method and put `#cameras` anywhere in the document, well those never get listed/indexed by `zk`. Doesn't matter if I put them at the beginning, under the title or at the end of the documented. So I just wonder how is the `#hashtag` method supposed to be used ? Where do I put those tags so they get indexed and are searchable by `zk` ?

**Comment by mickael-menu** [comment]
`zk` should be able to find your `#hashtag` anywhere in the note.

Here's a test I did today:

```sh
$ zk init
? Do you prefer [[WikiLinks]] over regular Markdown links? No
? Choose your favorite inline tag syntaxes: #hashtag

Initialized a notebook in /tmp/test

$ echo "#tag" > test.md

$ zk tag list
tag (1)

Found 1 tag
```

Could you share your config file under `.zk/config.toml`?

You should have this in it:

```toml
[format.markdown]
hashtags = true
```

**Comment by rafamadriz** [comment]
> You should have this in it:
> ```toml
>    [format.markdown]
>    hashtags = true
>```

Oh finally it works, for some reason it was set to false even though I selected the `#hashtag` syntax when creating the notebook, I didn't touch the config file at all. Thanks for your help!
