### ISSUE TITLE
Idea: Create links for things that do not exist.

### ISSUE THREAD

**Issue by mbriggs** [mickael-menu/zk#135]
Been really been liking zk, trying to migrate off of craft.do.

Something I really like about craft is the ability to link to things that do not exist yet. I will create links for most nouns and ideas even if I don't have content yet to collect backlinks.

I feel like I can accomplish this today with what exists with some lua in nvim, but it will be kind of hacky, and I feel like this is something that could be better.

What I am thinking is a key to surround a selection with `[[ ]]`. If a diagnostic appears, call a function that:
- captures the title in the wiki link
- create new note with `insertLinkAtLocation`
- capture the file name of the buffer
- go back to the previous buffer
- find the link inserted by zk
- remove the extra set of `[[ ]]`
- replace the file name with the captured title text

is this a use case that you think is a good idea? I would imagine it would be better (and maybe easier) to implement this in zk itself, maybe as a code action. If you are into it, I'll work on a PR instead of the above hacky lua function :)

**Comment by mickael-menu** [comment]
Yes I thought of adding stuff to handle "ghost/virtual" notes, especially to see all the backlinks associated to it.

I'm not sure I understand exactly the steps you described though. There's already a code action to create a new note from a selection.

Do you want to add a code action to create a new note (including generating a filename) from an already existing `[[title]]` link in a note, if it is reported as "not found"?

**Comment by skbolton** [comment]
Same as #28

**Comment by mickael-menu** [comment]
Good point, thanks. I'll close this one as duplicate. Feel free to chime in in #28 @mbriggs
