### ISSUE TITLE
Regenerate book using new filename and link format rules ?

### ISSUE THREAD

**Issue by thecontinium** [mickael-menu/zk#136]
Hi

Once a notebook has been created is it possible to regenerate the files and associated links in those files using new filename and link formatting rules ?

cheers

**Comment by mickael-menu** [comment]
You can't do this with `zk` and I don't think I want to add such feature. However, I think it should be relatively easy to write a script to do this using:

* `zk new --dry-run` and a template to generate a filename, see something similar here https://github.com/mickael-menu/zk/issues/93
* `zk rename` to rename a note, unfortunately it's not yet implemented.
