### ISSUE TITLE
Allow different options for FzF in interactive filtering

### ISSUE THREAD

**Issue by Nelyah** [mickael-menu/zk#137]
Thank you for  the tool, it is a brilliant piece of software which I'm enjoying very much!

One of thing I wish would be possible is adjusting the FZF parameters. The one I'm thinking most is `--height 40%` (instead of 100% in `zk edit -i`). I've looked a bit at the code and it seems to be set in `internal/adapter/fzf/fzf.go:75`. 

One solution would be to prepend that list of arguments with the env variable `$FZF_DEFAULT_OPTS` if it exists, and append to the list custom options that could be defined in the `.zk/config.toml`. This would make the default config for fzf in zk override the default `fzf` config (makes sense to me) but would still allow users to override the `zk` default config (`fzf --height 100% --height 40%` results in height at 40%).

Do you think this would be possible?

**Comment by mickael-menu** [comment]
> Thank you for the tool, it is a brilliant piece of software which I'm enjoying very much!

Thank you for the kind words!

> One solution would be to prepend that list of arguments with the env variable `$FZF_DEFAULT_OPTS` if it exists, and append to the list custom options that could be defined in the `.zk/config.toml`. This would make the default config for fzf in zk override the default `fzf` config (makes sense to me) but would still allow users to override the `zk` default config (`fzf --height 100% --height 40%` results in height at 40%).

That sounds like a good strategy. The user options could be specified [in the configuration file](https://github.com/mickael-menu/zk/blob/main/docs/tool-fzf.md#integration-with-fzf):

```toml
[tool]
fzf-options = "--height 40%"
```

Would you be interested in contributing a PR for this?

**Comment by Nelyah** [comment]
I will try to see in the next few days if I can come up with something, though I have never really written a single line of Go before. 

The issue doesn't seem _too_ complicated though, so maybe I'll be able to get something working and this would be a good introduction to the language. I'll let you know how this goes!

**Comment by mickael-menu** [comment]
Thanks, you can create a draft PR and if you check the "Allow edit from maintainers" checkbox while creating the PR I can finish it for you if needed.

**Comment by mickael-menu** [comment]
[`fzf-options`](https://github.com/mickael-menu/zk/blob/main/docs/tool-fzf.md) is now available in `main`.
