### ISSUE TITLE
Tests failing due to missing tags

### ISSUE THREAD

**Issue by grawlinson** [mickael-menu/zk#141]
Hi! When packaging this for Arch Linux, I ran into sqlite/fts5 issues with the tests and I figured out it was because I wasn't passing the required tags to `go test`.

I thought you may be interested in case this issue pops up for you.

The fix is [here](https://github.com/archlinux/svntogit-community/blob/7e5f05b0080d66b9aa8eeeb1e778a4d8cc1aa628/trunk/PKGBUILD#L51).

**Comment by mickael-menu** [comment]
Thanks, this is indeed a frequent issue when building manually the project.
