### ISSUE TITLE
LSP auto-completion of YAML frontmatter tags

### ISSUE THREAD

**Issue by mickael-menu** [mickael-menu/zk#144]
> Hello!
> Is it planned to add auto-complete on tags in the YAML frontmatter? 
> It works well when added with `#` but I use them only in the frontmatter.
> _Originally posted by @tissieres in https://github.com/mickael-menu/zk/issues/22#issuecomment-1005521297_

**Comment by mickael-menu** [comment]
LSP auto-completion needs a trigger character, which is easy with `#hashtags` and `:colon:tags:`, but not with the YAML frontmatter since there's no character distinguishing tags.

A possible workaround would be to use `#` for the trigger character, and if we detect that we are inside a YAML frontmatter, request the editor to remove it after insertion. Not super straightforward but feasible, I think this would be useful to have in `zk`.

**Comment by kabouzeid** [comment]
This is not completely true. Completion is also automatically triggered when typing an identifier, and it can of course always be manually triggered by the user. See (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionOptions) and (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionTriggerKind).

I've just checked that Neovim will in fact send a complete request when starting to type a tag name (identifier) in the frontmatter. VSCode does the same. This is from the logs:
```
[DEBUG][2022-01-05 20:32:24] .../vim/lsp/rpc.lua:347	"rpc.send"	{  id = 36,  jsonrpc = "2.0",  method = "textDocument/completion",  params = {    context = {      triggerKind = 1    },    position = {      character = 7,      line = 2    },    textDocument = {      uri = "file:///home/karim/Documents/Zettelkasten/index.md"    }  }}
```
Notice that `context.triggerKind` is set to `1` in this case.

**Comment by mickael-menu** [comment]
Ha that's interesting, do you know if there's a way to request a specific kind of completion item from the client?

**Comment by kabouzeid** [comment]
I'm not sure I understand what you mean. The client can (and usually does) filter and sort the completion results locally according to user prefs. But how would that help here?

**Comment by mickael-menu** [comment]
No I mean how do you know whether to complete tags or links (not a great example, but more completion items might be added later on) from the LSP server when receiving this?

Right now, I'm using the value of the `triggerCharacter` for this.

Or maybe the server is supposed to check the location of the caret to infer the kind of item to complete?

**Comment by kabouzeid** [comment]
> Or maybe the server is supposed to check the location of the caret to infer the kind of item to complete?

Yes :)

**Comment by mickael-menu** [comment]
I think it would be pretty trivial to support for:

```
tags: [a, b]
```

But YAML bullet lists would require more work:

```
tags:
  - a
  - b
```

**Comment by kabouzeid** [comment]
Kind of hacky, but relatively easy and might work very well: 
On the server side, we could insert some random string at the completion position, then parse the yaml and see if the inserted random string would be parsed as a tag.

**Comment by mickael-menu** [comment]
Yeah that should work fine.

**Comment by mickael-menu** [comment]
Could you check this out https://github.com/mickael-menu/zk/pull/146? I implemented your idea @kabouzeid, it works well but requires the YAML frontmatter to be valid, so if you have a hanging `[` or `"`, it won't auto-complete.

**Comment by mickael-menu** [comment]
cc @tissieres

**Comment by tissieres** [comment]
Hi @mickael-menu 
Just tested it and it works perfectly for me. BTW, I'm using a template with a valid frontmatter at the beginning:
```
tags: []
```
Thanks very much!
