### ISSUE TITLE
LSP configuration for ale

### ISSUE THREAD

**Issue by lowski** [mickael-menu/zk#155]
Hey!
Thank you for this app. It's great!

I'm using regular Vim with [Ale](https://github.com/dense-analysis/ale) for linting, fixing and LSP. It works fine for built-in languages like TypeScript or Elixir but when I added custom configuration for zk notes like this:

```
function! GetProjectRootForZk(buffer) abort
    let l:zk_path = ale#path#FindNearestDirectory(a:buffer, '.zk')

    return !empty(l:zk_path) ? fnamemodify(l:zk_path, ':h:h') : ''
endfunction

set omnifunc=ale#completion#OmniFunc

call ale#linter#Define('markdown', {
         \ 'name': 'zk_language_server',
         \ 'lsp': 'stdio',
         \ 'executable': '/usr/local/bin/zk',
         \ 'command': ''/usr/local/bin/zk lsp --log /tmp/zk-lsp.log',
         \ 'project_root': function('GetProjectRootForZk')
         \ })
```

I don't see any completion when I type `[[`. I also tried `CTRL-X CTRL+O` for omnicompletion but I only see `Pattern not found`.

`ALEHover` works correctly as it shows linked note in the preview when I call it on the some `[[link]]` (I use wiki format).

I'm aware that `ale` might not be a popular plugin anymore but I would highly appreciate any pointers. Thank you!

**Comment by mickael-menu** [comment]
I'm not sure I can help as I'm not familiar with `ale`.

Could you share your `/tmp/zk-lsp.log` file after entering `[[` and also triggering completion manually?

**Comment by lowski** [comment]
Sorry for being inactive. It looked like Ale was pushing the whole file content for completion. I eventually switched to Neovim and settled on official zk plugin. Thank you!
