### ISSUE TITLE
Feature Request - Quick note with single command

### ISSUE THREAD

**Issue by zhengpd** [mickael-menu/zk#158]
It would be helpful to allow quick note with single command like `zk new 'Content of one-line note'`, creating a new one-line note quickly.

**Comment by mickael-menu** [comment]
Assuming that you are using a [template](https://github.com/mickael-menu/zk/blob/main/docs/template-creation.md) containing at least the `{{content}}` variable, you can pipe in the content of your note like this:

```sh
$ echo "Content of one-line note" | zk new --title "Title of the note"
```

If you call this often, you might want to add [a new alias](https://github.com/mickael-menu/zk/blob/main/docs/config-alias.md) in your config file:

```toml
[alias]
quick = 'echo $2 | zk new --title $1'
```

Then you can use:

```sh
$ zk quick "Title of the note" "Content of one-line note"
```

If you don't care for the note title, I suggest using this alias:

```toml
[alias]
quick = 'echo "$*" | zk new'
```

With this, you don't even need the quotes around your note content:

```sh
$ zk quick Content of one-line note
```

Let me know if it helps.

**Comment by zhengpd** [comment]
@mickael-menu Really helpful!
