### ISSUE TITLE
Add flag to override id of new note

### ISSUE THREAD

**Issue by skbolton** [mickael-menu/zk#159]
It would be awesome if there was an --id flag that could be passed when generating a new note that would bypass the id generation rules. My use case is that I am starting to create notes for tickets I am assigned at work. Its pretty trivial to extract ticket IDs from branch names and open associated notes. I tried mapping tickets IDs to zk ids bit it was messy. And I also didn't want to introduce more tags to the system for these ephemeral ticket numbers.

For now I have gotten by using --dry-run and piping the output to a file with the id name I want. But I have to hardcore paths and I miss the path goodness zk gives. I think this could be a feature that is worthwhile to have. I could also contribute it if you are okay with the idea.

**Comment by skbolton** [comment]
I suppose another compromise could be changing the filename template for these notes to go off of extra.id

**Comment by mickael-menu** [comment]
> I suppose another compromise could be changing the filename template for these notes to go off of extra.id

Yes that's what I was going to suggest. Of course that means that you will need to manage two set of filename/note templates.

I wouldn't mind having an `--id` flag to override the default generated ID though. Feel free to open a pull request if you want to contribute it, thanks!

**Comment by skbolton** [comment]
Cool looking through the code now and I feel pretty confident that I can get this done no problem.

**Comment by skbolton** [comment]
Trying to work through this but running into issues. I have made a plan for how to implement and test this I just can't get `make tesh` to run.

Every tesh test fails with this warning.

```
zk: error: failed to open notebook: failed to migrate the database: database migration failed: no such module: fts5
```

I was also having errors running any of the other make commands in the project as well. If I try to run
```
make
```

Then I get this error
```
CGO_ENABLED=1 go build -tags "fts5 icu" -ldflags "-X=main.Version=`git describe --tags --match v[0-9]* 2> /dev/null` -X=main.Build=`git rev-parse --short HEAD`"
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3Fts5IndexQuery’:
sqlite3-binding.c:226545:18: warning: ‘memcpy’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
226545 |     if( nToken ) memcpy(&buf.p[1], pToken, nToken);
       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The only way I have found around this was spedifying an older gcc version.

```
CC=gcc-10 make 
```

Sadly this hasn't worked so for `tesh`

```
CC=gcc-10 make tesh
```

**Comment by skbolton** [comment]
Of course right after posting this I get it working. This is what is making it so that I can now run `make tesh`

```
CC=gcc-10 go install --tags "icu json1 fts5 secure_delete"
```

```
CC=gcc-10 make tesh
```

I'll finish up this feature and do more research into this.
