### ISSUE TITLE
bubble-up search for nested tags

### ISSUE THREAD

**Issue by edrex** [mickael-menu/zk#161]
Hi, just started testing this tool, and I hit a small snag.

Obsidian and Emanote's tag filter operators include results from descendant tags (so searching for `#project` includes notes tagged `#project/active/ongoing` etc). Semantically, a note which is tagged with a descendant is considered to have all ancestor tags too.

A fragment of my tag heirarchy:

- #project 
  - #project/active
    - #project/active/ongoing
  - #project/somedayMaybe
  - ...

My first suggestion would be to change the behavior of the tag filter operator to that `zk list -t project` returns results for descendant tags too. Alternatively, a different operator could be introduced supporting bubble-up.

**Comment by mickael-menu** [comment]
Try appending a wildcard to your tag name to match a prefix:

```
zk list -t project*
```

You can find [more operators in the documentation](https://github.com/mickael-menu/zk/blob/main/docs/note-filtering.md#filter-by-tags).

**Comment by edrex** [comment]
Thanks. I guess the exact search would be `project OR project/*`. From a string matching point of view this is sufficient. 

Food for thought: I still feel like taking a stance on the semantics of nested tags is important: they're not just strings, they're nodes in a tree. The other two projects define the semantics of containment to bubble up, which means a large portion of the userbase is trained to think about them this way. Anyway, I'm only interested to provide useful feedback and not give you grief on your project, so I'll close this and if you decide it's important you could always reopen

**Comment by mickael-menu** [comment]
What would be the ideal behavior of `zk` according to you?

I wouldn't want to make `-t project` match both `project` and `project/active`, but I guess adding an operator like `-t project/` that would be an alias to `project OR project/*` could be useful.

**Comment by edrex** [comment]
> What would be the ideal behavior of zk according to you?

IMO ideal would be having some concise/expressive way of asking for a match on all descendant tags, while still preserving the existing exact match search


> I wouldn't want to make -t project match both project and project/active, but I guess adding an operator like -t project/ that would be an alias to project OR project/* could be useful.

Using a trailing slash as an alias sounds good, or maybe just adding another flag `-T` seems more [explicit](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python) (I always have to look at the rsync manpage for how trailing slash affects rsync).
