### ISSUE TITLE
Make filename match file title

### ISSUE THREAD

**Issue by johnsonlab** [mickael-menu/zk#162]
My convention (for better or for worse) has been to have the [[wiki-linked]] filenames match the file title where for file This.is.my.file1.md:

---

# This.is.my.file1

lorem ipsum...

[[This.is.my.file2]]

---

Can this be achieved in the config.toml 

filename= 

setting easily? Thanks!!

**Comment by mickael-menu** [comment]
I'm not sure I fully understand, could you write down the full `zk` command you use to create the note, and your expected filename and title?

**Comment by johnsonlab** [comment]
I just installed zk and am using the default zk command that produces the random 4 character string for md filenames. As you'd expect, my file titles are descriptive. Historically, using atom and the wikilinks plugin, my markdown filenames are exactly the same as the file title in the top line of the .md file after a #, as follows:

**Title of .md file:**
          # Same.as.filename 

**Saved name as .md file:**
          Same.as.filename.md

Switching to the four-character zk default will take some adjustment (and wouldn't be impossible). My question is whether zk can have the filename exactly match the title as hopefully clarified here. Basically, is there a zk command that would use the Title as the filename? Thanks!!

**Comment by mickael-menu** [comment]
Ha, sure. You can add this to your config:

```toml
[note]
filename = "{{title}}"
extension = "md"
```

Then create a note with `zk new --title "Same.as.filename"`
