### ISSUE TITLE
Feature request: customize which shell is used to execute aliases

### ISSUE THREAD

**Issue by j-hui** [mickael-menu/zk#163]
I usually use Fish as my interactive shell, but the example aliases given use Bash syntax. For example:

```
ls = "zk list $@"
```

While I could change this to `zk list $argv`, I would instead like to specify which shell to use (instead of having it be determined by `SHELL`). This way, the same aliases will work whether I'm using Bash or Fish or any other shell.

**Comment by mickael-menu** [comment]
I guess I could add a config option like I did for `PAGER`, but I'd like to understand better your issue. Why do you need to use a different `SHELL` value for `zk` compared to the regular shell?

**Comment by j-hui** [comment]
> I guess I could add a config option like I did for PAGER

That would be perfect.

> I'd like to understand better your issue. Why do you need to use a different SHELL value for zk compared to the regular shell?

To elaborate: fish does not support `$@` syntax. Instead, it uses `$argv`.

Personally, I don't really like this about fish, but then again, I don't use it for scripting. I'd like to stick to POSIX shell syntax for zk aliases while still using fish as my interactive shell.

[sxhkd has also encountered this issue](https://wiki.archlinux.org/title/bspwm#Problems_with_keybindings_using_fish), which it worked around using the [`SXHKD_SHELL` environment variable](https://github.com/baskerville/sxhkd/issues/161). I'm looking for a similar workaround.

**Comment by mickael-menu** [comment]
I added `ZK_SHELL` in `main`, it was simpler than adding another config option for this.

**Comment by j-hui** [comment]
Awesome, thanks!

**Comment by ivanddm** [comment]
Hi,
How do I use this setting? I tried setting `set -x ZK_SHELL "/bin/bash"` in my fish config but still aliases are run with fish shell.

**Comment by mickael-menu** [comment]
I think you need the `-g` option with fish:
https://fishshell.com/docs/current/tutorial.html#exports-shell-variables
```
set -gx ZK_SHELL "/bin/bash"
```

**Comment by ivanddm** [comment]
Since I'm setting the env variable outside a function, it really doesn't matter (`-x` or `-gx`). Nonetheless, I tried with `-gx` as well but still aliases are not run with the specified shell.

**Comment by mickael-menu** [comment]
What do you see if you run `zk` like this? (Assuming you have this alias `ls = "zk list $@"`)

```sh
ZK_SHELL=echo zk ls
```

**Comment by ivanddm** [comment]
Sorry, I'm not sure what you mean. If I run `zk` I get the `zk` usage message regardless whether I set `ZK_SHELL` to `echo zk ls`. In fish it would be `set -gx ZK_SHELL $(echo zk ls)`. If I run `zk ls` I get the following:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/20104703/166260416-21bf90ac-30f4-425f-b90a-9d692f9c2d05.png">

**Comment by mickael-menu** [comment]
I installed fish and it seems to work for me. This is what I meant:

<img width="703" alt="Screenshot 2022-05-02 at 17 35 53" src="https://user-images.githubusercontent.com/58686775/166262630-b3867a6c-0bda-4dae-a83c-81543196bfe9.png">

**Comment by ivanddm** [comment]
Ok, so apparently I had an older version when I installed `zk` with `brew install zk`, which was a couple of days ago so I though it had pulled the latest version. I reinstalled `zk` with `brew install --HEAD zk` and now it is working as desired 👍🏻... Thanks a lot for your time and for putting together a really nice app.

**Comment by mickael-menu** [comment]
Hmm yes, it looks like the Homebrew version was not updated automatically with the release, I need to take a look into that. Thanks for spotting this.

**Comment by mickael-menu** [comment]
Looks like someone already created it, so it should be available now: https://github.com/Homebrew/homebrew-core/pull/100286

**Comment by ivanddm** [comment]
Yes, I uninstalled and reinstalled with just `brew install zk` and it is picking up the 0.10.0 version. Thanks again!
