### ISSUE TITLE
search for `§§` in notes

### ISSUE THREAD

**Issue by danymat** [mickael-menu/zk#164]
Hello, I'm using the zk-nvim companion and it works wonderfully !

My starting notes have all `§§` inside them, as this one:

```
## 202105131259 Deep Work
##§2 #newport2016 §§ ##deep-work

## Pourquoi

...
```

I tried using `zk list -e "§§"` (or with `-m`), without success. Am I missing something here ?

**Comment by mickael-menu** [comment]
> Hello, I'm using the zk-nvim companion and it works wonderfully !

Yeah I'm quite happy with it as well!

> I tried using `zk list -e "§§"` (or with `-m`), without success. Am I missing something here ?

You need both actually, try with `zk list -em "§§"`.

`-e/--exact-match` is just a boolean flag to enable literal matching, but you still need to provide an actual query with `-m/--match`.

**Comment by danymat** [comment]
Nice, it works well ! thanks !
