### ISSUE TITLE
note.ignore option does not ignore subdirectories

### ISSUE THREAD

**Issue by j-hui** [mickael-menu/zk#173]
I seem to be unable to ignore all subdirectories under a path. Steps to reproduce:

```shell
$ zk init --no-input
...
$ edit .zk/config.toml
...
$ cat .zk/config.toml
[note]
template = "default.md"
ignore = [
  "drafts/**",
  "log.md"
]
[format.markdown]
link-format = "wiki"
hashtags = true
colon-tags = false
multiword-tags = false
[lsp]
[lsp.diagnostics]
dead-link = "error"
$ mkdir -p drafts/subdir
$ echo "# This is not ignored" > not-ignored.md
$ echo "# This is ignored" > drafts/ignored.md
$ echo "# This should be ignored but isn't" > drafts/subdir/should-ignore.md
$ zk list
This is not ignored not-ignored.md (1 minute ago)


This should be ignored but isn't drafts/subdir/should-ignore.md (just now)



Found 2 notes
```

This also doesn't work with `drafts/*`. It sort of works with `drafts/*/*` but then `drafts/ignored.md` is not ignored.

**Comment by mickael-menu** [comment]
This is the default behavior of Go's globbing, but I agree it's not great. I'll take a look if it can be improved.

**Comment by mickael-menu** [comment]
It's now available in `main`, I used a third-party lib to support the double star globbing.

**Comment by trev-dev** [comment]
The double globbing is not working recursive for me, currently using "zk dev" on nixos.

**Comment by mickael-menu** [comment]
@trev-dev Could you share a minimal reproducible example on how it fails? I'll check with the latest `zk` version to rule out an issue in it.

**Comment by trev-dev** [comment]
@mickael-menu I am not sure what changed on my end but I can no longer reproduce the issue myself.  I will return here if I can

**Comment by trev-dev** [comment]
@mickael-menu Actually, I *do* know what changed.  I use nixos and my config is symlinked by the build daemon :roll_eyes: I must have forgotten to rebuild my home env but I have re-built since I originally commented.
