### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by vod3** [mickael-menu/zk#178]
Hi, after installing `libicu-dev` on Fedora 35 (which is called `libicu-devel`) and trying to make the src folder, I get this error:

```
$ make      
CGO_ENABLED=1 go build -tags "fts5 icu" -ldflags "-X=main.Version=`git describe --tags --match v[0-9]* 2> /dev/null` -X=main.Build=`git rev-parse --short HEAD`" 
../.local/share/go/pkg/mod/github.com/gosimple/unidecode@v1.0.0/table.go:1:1: expected 'package', found 'EOF'
../.local/share/go/pkg/mod/github.com/rivo/uniseg@v0.2.0/properties.go:1:1: expected 'package', found 'EOF'
../.local/share/go/pkg/mod/github.com/mickael-menu/glsp@v0.1.1/protocol_3_16/language-features.go:1:1: expected 'package', found 'EOF'
../.local/share/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/chacha20/vectors_test.go:1:1: expected 'package', found 'EOF'
../.local/share/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/internal/poly1305/vectors_test.go:1:1: expected 'package', found 'EOF'
../.local/share/go/pkg/mod/golang.org/x/sys@v0.0.0-20211002104244-808efd93c36d/unix/syscall_linux.go:1:1: expected 'package', found 'EOF'
make: *** [Makefile:3: build] Error 1

```

Am I missing some dependencies?
Thank you!

**Comment by vod3** [comment]
in addition, this is what happens when I try to execute the zk binary:
`./zk --debug
./zk: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory
`

**Comment by mickael-menu** [comment]
@vod3 Did you find the reason of the initial issue? It looks like maybe an incompatible Go version or corrupted / incomplete Go dependencies.

For the second issue, you should not get it if `zk` is built on the same machine as it's running, or with a machine using the same version for `libicu-dev`. You might want to look into which versions you use.

**Comment by skbolton** [comment]
I am working through trying to implement #159 and running into similar issues running tests and building the project. One thing I have seen work for me is specifying the gcc version to version 10. My system (Arch Linux) is currently on version 11 and I can't get it to run with that. This works though.

```
CC=gcc-10 make build
```

Still can't get `CC=g-10 make tesh to work` but I'll chime in about that on the original issue I mentioned.

**Comment by maxmahlke** [comment]
`make` failed for me with a `go` dependency error as well. I am running Ubuntu LTS 18.3 and the `go` version in the repositories is `1.10`. I downloaded a current `go` version from https://go.dev/doc/install and ran (following the instructions on the page)

`rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz`

I further replaced the `/usr/bin/go` executable on my system with the one in the `tar.gz` file. Now I have

```
$ go version                                                                                                                                                                           main
go version go1.18 linux/amd64
```

and now, running `make` worked for me.
