### ISSUE TITLE
LSP Hover breaks on windows

### ISSUE THREAD

**Issue by dstanberry** [mickael-menu/zk#184]
I'm using neovim on windows and when I attempt to hover over a tag, the request fails with something similar to the following:
```
zk: -32600: parse "file:///C:%5Cfoo%5Cbar.md": invalid port "%5Cfoo%5Cbar.md"
```

The `%5C` is html escaped 'somewhere' which causes uriToPath(...) to fail:

https://github.com/mickael-menu/zk/blob/a0ced3c33098a813dcb803e350b2ea38aa79ce4b/internal/adapter/lsp/util.go#L19-L23

I've resolved this by doing a strings.ReplaceAll() and can submit a PR if you think this change is acceptable. There's probably a better/cleaner way to do this but I stopped at "this works for me".
```go
package lsp

import(
    ...
    "strings"
    ...
)

...

func uriToPath(uri string) (string, error) {
	s := strings.ReplaceAll(uri, "%5C", "/")
	parsed, err := url.Parse(s)
	if err != nil {
		return "", err
	}
```

**Comment by dstanberry** [comment]
It turns out the 'fix' I came up with was incomplete. There's a weird scenario with url.Parse() when the file scheme has only two forward slashes  instead of three. i.e. `"file:///"` vs `"file://"`. FWIW, I found this related issue https://github.com/golang/go/issues/13276.

I'm not experienced with golang and I'll admit this seems a bit hacky but it's finally consistent with the following changes made:

```go
func uriToPath(uri string) (string, error) {
	s := strings.ReplaceAll(uri, "%5C", "/")
	parsed, err := url.Parse(s)
	if err != nil {
		return "", err
	}
	if parsed.Scheme != "file" {
		return "", errors.New("URI was not a file:// URI")
	}

	if runtime.GOOS == "windows" {
		// In Windows "file:///c:/tmp/foo.md" is parsed to "/c:/tmp/foo.md".
		// Strip the first character to get a valid path.
		if strings.Contains(parsed.Path[1:], ":") {
			//url.Parse() behaves differently with "file:///c:/..." and "file://c:/..."
			return parsed.Path[1:], nil
		} else {
			// if the windows drive is not included in Path it will be in Host
			return parsed.Host + "/" + parsed.Path[1:], nil
		}
	}
	return parsed.Path, nil
}
```

**Comment by mickael-menu** [comment]
Hi @dstanberry, thank you for spotting this. Feel free to open a PR with your fix.
