### ISSUE TITLE
Broken OSX release

### ISSUE THREAD

**Issue by pwntester** [mickael-menu/zk#189]
Hi,

I was using a self built `zk` instance (using `go install --tags "icu json1 fts5 secure_delete"`) and that was working ok on OSX. I recently switched to [`nvim-lsp-installer`](https://github.com/williamboman/nvim-lsp-installer/blob/e8530f4059279a0d6b5e5f8891d04ffb1ade29a3/lua/nvim-lsp-installer/servers/zk/init.lua) which just grabs the OSX release and that executable throws the following error when run:

```
dyld[36613]: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.69.dylib
  Referenced from: /Users/pwntester/Downloads/zk
  Reason: tried: '/usr/local/opt/icu4c/lib/libicuuc.69.dylib' (no such file), '/usr/local/lib/libicuuc.69.dylib' (no such file), '/usr/lib/libicuuc.69.dylib' (no such file), '/usr/local/Cellar/icu4c/70.1/lib/libicuuc.69.dylib' (no such file), '/usr/local/lib/libicuuc.69.dylib' (no such file), '/usr/lib/libicuuc.69.dylib' (no such file)
```

I checked that the one distributed with homebrew also works ok and that `/usr/local/Cellar/icu4c/70.1/lib/libicuuc.70.dylib` is installed but the OSX github release is looking for version 69

Thanks

**Comment by mickael-menu** [comment]
Unfortunately the ICU lib is linked dynamically with `zk`, and linking statically is complicated (see https://github.com/mickael-menu/zk/discussions/76#discussioncomment-1419379).

This means that at some point the pre-built release binaries will get obsolete. Until we find a better solution, the preferred way to install `zk` is to build it yourself.

**Comment by pwntester** [comment]
Thanks for the reply @mickael-menu will future releases use latest ICU version?

**Comment by mickael-menu** [comment]
Yeah, I will upgrade my `icu4c`.

**Comment by pwntester** [comment]
Thanks!
