### ISSUE TITLE
Parsing YAML frontmatter fails when frontmatter is terminated by "..." instead of "---"

### ISSUE THREAD

**Issue by bit-hug** [mickael-menu/zk#190]
The [YAML specification](https://yaml.org/spec/1.2.2/) defines two ways of terminating a document: `---` and `...`.

`zk` successfully recognizes `---` both as initiator and terminator of YAML frontmatter, using the following regular expression.

https://github.com/mickael-menu/zk/blob/3b05a0061df04e653de7f7b178964ff7f1889ed3/internal/adapter/markdown/markdown.go#L303

However, `zk` does not recognize `...` as a terminator of YAML frontmatter.

The majority of the tags in my markdown files are defined in YAML frontmatter terminated by `...`, and as such `zk` detects none of them.

If the above regex were replaced with, for instance, `(?ms)^\s*-+\s*$.*?^\s*[-\.]+\s*$`, then `zk` would successfully recognize both ways of terminating YAML frontmatter.

**Comment by mickael-menu** [comment]
That makes sense. Would you mind opening a PR to fix this? You can add a new test case using `...` in this directory: https://github.com/mickael-menu/zk/tree/main/tests/fixtures/yaml-frontmatter

and this tesh test file: https://github.com/mickael-menu/zk/blob/main/tests/markdown-yaml-frontmatter.tesh It will be run automatically in the GitHub action. Thanks!

**Comment by mickael-menu** [comment]
I tried implementing this, but it doesn't fully work because [goldmark](https://github.com/yuin/goldmark), the third-party Markdown parser I'm using, doesn't support `...`. I suggest opening an issue there to request this feature and if it's implemented, we can reopen this one.
