### ISSUE TITLE
Linux terminal borked when using aliases

### ISSUE THREAD

**Issue by artoj** [mickael-menu/zk#201]
## Output of zk --version

0.10.0-1-g94f563c

## OS / environment

Ubuntu 20.04, Gnome, Gnome terminal, bash

## How did you run zk?

```
zk edi
```

In ~/.config/zk/config.toml I have this alias:

```
edi = "zk edit --interactive $@"
```

## Problem description

When I run `zk edi`, fzf opens, but the terminal is borked. It's as if every other typed character goes to fzf and every other character disappears. fzf is installed through the package manager.

There's no issue if I run without alias, i.e. `zk edit --interactive`. I cannot reproduce the issue on my macOS Big Sur machine.

**Comment by mickael-menu** [comment]
Hi,

I'm not sure what would cause this issue and unfortunately I can't test this out on Linux. If someone else has this issue and is willing to take a look, the aliases are executed here:

https://github.com/mickael-menu/zk/blob/94f563cd51dc4dffd0a4c5e0e1c9e8d7c68996ba/main.go#L182-L195

**Comment by artoj** [comment]
I managed to test this on another Ubuntu machine and I cannot reproduce the issue. The problem is on my end. I'll close this.
