### ISSUE TITLE
Cannot run the latest 0.10 release in Ubuntu 22.04

### ISSUE THREAD

**Issue by MrPeterLee** [mickael-menu/zk#211]
The application is reporting:

`./zk: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory`

Also attempted to build using `make`, error occurred when including the icu unicode dependency.

The Ubuntu 22.04 packages `libicu-dev` of version 70.1, which is higher than version 63, that was used to built the release.

Could you please upgrade the dependency of build to the latest libicu-dev library? Thanks.

**Comment by mickael-menu** [comment]
The ICU dependency causes recurring build issues with `zk`. I'll take a look if I can do without, I believe so.

**Comment by afranioce** [comment]
I've got the same problem, but I'm using the Pop OS 21.10, I tried to install the `libicu67` and `libicu-dev`

**Comment by mickael-menu** [comment]
I managed to remove the dependency on libicu, you can try again from the `main` branch, or use these pre-built binaries:

* [zk-v0.10.0-6-g3c634fb-linux-amd64.tar.gz](https://github.com/mickael-menu/zk/files/8692604/zk-v0.10.0-6-g3c634fb-linux-amd64.tar.gz)
* [zk-v0.10.0-6-g3c634fb-linux-arm64.tar.gz](https://github.com/mickael-menu/zk/files/8692605/zk-v0.10.0-6-g3c634fb-linux-arm64.tar.gz)
* [zk-v0.10.0-6-g3c634fb-linux-i386.tar.gz](https://github.com/mickael-menu/zk/files/8692606/zk-v0.10.0-6-g3c634fb-linux-i386.tar.gz)
* [zk-v0.10.0-6-g3c634fb-macos-arm64.zip](https://github.com/mickael-menu/zk/files/8692607/zk-v0.10.0-6-g3c634fb-macos-arm64.zip)

Let me know if this solves the issue for you.

**Comment by JafarAbdi** [comment]
> I managed to remove the dependency on libicu, you can try again from the `main` branch, or use these pre-built binaries:
> 
>     * [zk-v0.10.0-6-g3c634fb-linux-amd64.tar.gz](https://github.com/mickael-menu/zk/files/8692604/zk-v0.10.0-6-g3c634fb-linux-amd64.tar.gz)
> 
>     * [zk-v0.10.0-6-g3c634fb-linux-arm64.tar.gz](https://github.com/mickael-menu/zk/files/8692605/zk-v0.10.0-6-g3c634fb-linux-arm64.tar.gz)
> 
>     * [zk-v0.10.0-6-g3c634fb-linux-i386.tar.gz](https://github.com/mickael-menu/zk/files/8692606/zk-v0.10.0-6-g3c634fb-linux-i386.tar.gz)
> 
>     * [zk-v0.10.0-6-g3c634fb-macos-arm64.zip](https://github.com/mickael-menu/zk/files/8692607/zk-v0.10.0-6-g3c634fb-macos-arm64.zip)
> 
> 
> Let me know if this solves the issue for you.

I had the same issue on Debian unstable using the binary from the link provided fixes the issue for me, thanks!

**Comment by mickael-menu** [comment]
Thanks, I'd like to fix an issue I noticed first and then I'll do a patch release.
