### ISSUE TITLE
A way to fix broken links after a rearrangement.

### ISSUE THREAD

**Issue by ktkimit** [mickael-menu/zk#212]
Suppose that I have in the rood zk directory:

6upt12-a.md
b/9nfbnv-b.md

In the file "6upt12-a.md", I have an internal link to the file "9nfbnv-b.md" like

`[b](b/9nfbnv-b)`

At some point later, I want to rearrange them like:

6upt12-a.md
9nfbnv-b.md

That is, I want to move "9nfbnv-b.md" to the rood directory. Then, the internal link in the file "6upt12-a.md" will be broken.

Is there a way to fix these broken links after rearranging things? Something like a link only with note id (without its path), or ...

**Comment by mickael-menu** [comment]
It's not supported yet but I have an issue opened for this: https://github.com/mickael-menu/zk/issues/200

> Something like a link only with note id (without its path), or ...

It's not possible with Markdown links, however you can use Wiki links for this, e.g. `[[9nfbnv]]`. See https://github.com/mickael-menu/zk/blob/main/docs/note-format.md#markdown
