### ISSUE TITLE
default-title does not accept templates like filename does.

### ISSUE THREAD

**Issue by DhruvaSambrani** [mickael-menu/zk#214]
I would like to keep the title of my note as the current date, like how the filename can be set. However, default-title does not accept templates and simply puts the string as is.

Workarounds - 
1. Use an alias with title with date given by external tools like `date`

**Comment by mickael-menu** [comment]
You don't need to use `{{title}}` in your note template, you can use directly `{{date}}` like so:

```markdown
# {{date now "long"}}

Content
```

There's an example here: https://github.com/mickael-menu/zk/blob/main/docs/daily-journal.md#maintaining-a-daily-journal
