### ISSUE TITLE
`zk search` - a way to search for notebooks in any child directory of provided directory

### ISSUE THREAD

**Issue by DhruvaSambrani** [mickael-menu/zk#215]
This is a feature request to search for any notebooks in any of the child directories.
`zk search school` searches for zk notebooks in any child directories of `school` and pipes to fzf with a list of notebooks as a preview for each of them. If search directory is not provided, assume `.`

Workaround until then -
```bash
function zks() {
    find $1 -type d -name "\.zk" | xargs -I{} dirname "{}" | fzf --preview="zk -W {} list --limit 10 -f oneline"
}
```

**Comment by mickael-menu** [comment]
I'm not sure I fully understand the purpose, what are you using this command for exactly?

But just from what you described, I feel like this feature might be a bit too specific for `zk`, and I prefer to keep the commands focused on individual notebooks, a bit like `git`.

However, you can add a global alias in `~/.config/zk/config.toml`:

```toml
[alias]
search = 'find $1 -type d -name "\.zk" | xargs -I{} dirname "{}" | fzf --preview="zk -W {} list --limit 10 -f oneline"'
```

Then you can use it like you expected `zk search school`.

Other alternatives you can use:

1. Having a single notebook, and use subdirectories to contain your notes. When you are in a subdirectory, you can do `zk list .` to see only the notes in the directory.
2. Use nested notebooks. Add a `.zk` directory in a subdirectory to make its own notebook. The parent notebook will still see all the notes.
    * `zk init` doesn't work to create a nested notebook, but I might enable it as it could be a useful use case.

**Comment by DhruvaSambrani** [comment]
I didn't know there was a global config file. This solves the issue, thank you
