### ISSUE TITLE
Feature Request: Matching supports CJK characters

### ISSUE THREAD

**Issue by purefun** [mickael-menu/zk#220]
Because supporting CJK characters fts is complex, maybe adding a flag to `zk list` for grep is a simple solution. :)

**Comment by mickael-menu** [comment]
I initially thought of allowing grepping with an `--exec` flag (see https://github.com/mickael-menu/zk/issues/31), but this use case seems to important to not support it out of the box. I'll look into adding this.

It will probably look like this, to go with `--exact-match`:

```shell
$ zk list --re-match --match foo
$ zk list -Rm foo
```

Or maybe refactor this into having a `--match-strategy=re|exact`, which opens the door to other strategies like "fuzzy".

```shell
$ zk list --match-strategy re --match foo
$ zk list -Sre -m foo
```

**Comment by mickael-menu** [comment]
Here you go: https://github.com/mickael-menu/zk/pull/222, it's available in `main`.

You can set the default strategy with a [custom alias](https://github.com/mickael-menu/zk/blob/main/docs/config-alias.md):

```toml
[alias]
list = "zk list --match-strategy re $@"
```
