### ISSUE TITLE
links breaking after adding a new note via ZkNew

### ISSUE THREAD

**Issue by nathanbraun** [mickael-menu/zk#236]
Not sure if this is an zk-nvim or zk issue, but...

On initial db creation (if I delete notebook.db, then do zk index) all the links work fine. I can look at it in my db GUI and everything looks good.

However, if I add a new note using `:ZkNew`, all the values of `target_id` in the links table of notebook.db get updated to whatever the new note's ID is.

Everything goes back to working if I delete notebook.db then regenerate it, but that's obviously tedious to do.  Note adding a link seems to work fine, it's just creating a new note that is causing issues.

**Comment by mickael-menu** [comment]
@nathanbraun https://github.com/mickael-menu/zk/pull/237 (branch `issue-62`) should fix this issue, but I would appreciate if you could double check before I merge it. Thanks!

**Comment by nathanbraun** [comment]
> @nathanbraun #237 (branch `issue-62`) should fix this issue, but I would appreciate if you could double check before I merge it. Thanks!

Just tried it and it's working for me!  Thank you!

**Comment by nathanbraun** [comment]
Closed, but on second thought will let you close it when it's merged.  Looked good though
