### ISSUE TITLE
zk new not working anymore

### ISSUE THREAD

**Issue by tim-hilt** [mickael-menu/zk#244]
I upgraded to zk 0.11.0 (via Arch Linux' pacman), and suddenly I can't instantiate new notes with `zk new` anymore.

The exact command I used up until now was:

``` bash
zk new --no-input "$ZK_NOTEBOOK_DIR/daily"
echo $ZK_NOTEBOOK_DIR
> /home/tim/.dotfiles/notes/notes
```

when I run any `zk new`-command (including the one I showed above) it just hangs there without reacting anymore:

![Peek 2022-07-13 11-53](https://user-images.githubusercontent.com/16037579/178705984-59c2093b-0efb-498a-b7ba-9d18147293fc.gif)

Let me know if you need further information!

**Comment by mickael-menu** [comment]
Here you go https://github.com/mickael-menu/zk/releases/tag/v0.11.1
