### ISSUE TITLE
Unable to list by link and backlink

### ISSUE THREAD

**Issue by mhanberg** [mickael-menu/zk#254]
## Description

I am attempting to find all notes that are linked by or backlinked to a given note, but I am receiving the following error

```shell
┌─ 03:43:25 PM
│iCloud/notes/work
└─  zk list --link-to=azcb.md --linked-by=azcb.md
zk: error: ambiguous column name: l.snippet
```

Should this work?

**Comment by mickael-menu** [comment]
Thank you, it should be fixed in `main`.

**Comment by mhanberg** [comment]
Thanks, I appreciate it. I'll try again on monday.

**Comment by mhanberg** [comment]
Tried this out.

I expected this to be an "OR" operation, in that it would show me notes that are linking to the specified note, as well as notes that are linked by the specified note.

But it seems to be doing an "AND" operation, only returning notes that satisfy both conditions.

Is that expected?

**Comment by mickael-menu** [comment]
Yes that's expected, the CLI flags are additive (although I agree that for these two flags it might be less useful). You could add an alias like this to do two different queries:

```toml
anylink = "zk list -q --linked-by $@ && zk list -q --link-to $@"
```
