### ISSUE TITLE
Templating `lastweek` or `nextweek`

### ISSUE THREAD

**Issue by zalegrala** [mickael-menu/zk#256]
Howdy, great project!

I'm migrating everything from another Vim plugin I'd been using, and missing a couple template variables.  I have a `weekly` group where I track my work through the week, and the template has a link to next week and to last week.  I don't see this currently implemented, but was looking to see how it might be implemented.  Is this something you think would be a good contribution?

How is `yesterday` implemented for filtering?  I see a test for it, but not the implementation.

I also see `date now` and wondering where `now` is handled.  It looks like possibly coming from https://github.com/mickael-menu/zk/blob/main/internal/util/date/date.go#L15 but didn't find the template helper function to chase it down.  Would a `date lastweek` or something be the right approach or perhaps a `date now "lastweek"`?  What do you think?

**Comment by mickael-menu** [comment]
> How is `yesterday` implemented for filtering? I see a test for it, but not the implementation.

It's handled by https://github.com/tj/go-naturaldate, which supports "next week" or "last week" (with a space). You can use it with `zk list --created "last week"`, for example.

However, you can't use it with the [`{{date}}` template helper](https://github.com/mickael-menu/zk/blob/main/docs/template.md#date-helper), which has for signature `{{date <date variable> <format>}}` and is used to format a date as a readable string.

You could address this two ways:

* Either use the [`{{sh}} helper`](https://github.com/mickael-menu/zk/blob/main/docs/template.md#shell-helper) to generate the dates from a shell command.
* Add a new helper to compute a new date value from a natural date (like "last week"), that you could pass to `date`, e.g. `{{date (get-date "last week") "timestamp}}`.
    * I wish I named `{{date}}` as `{{format-date}}` instead...



> I also see `date now` and wondering where `now` is handled.

It's just a Handlebars template variable that is initialized with the current date: https://github.com/mickael-menu/zk/blob/c21c4fc21f7fe75f05d3fc3d09e74ffed41ba2ef/internal/core/note_new.go#L108

**Comment by zalegrala** [comment]
I wasn't able to build/test this, but let me know what you think.  It might work.  https://github.com/mickael-menu/zk/pull/262

**Comment by mickael-menu** [comment]
Thanks, I'll take a look this week-end.

**Comment by mickael-menu** [comment]
This was implemented in https://github.com/mickael-menu/zk/pull/262
