### ISSUE TITLE
missing Linux binaries in release assets break some 3rd party tools

### ISSUE THREAD

**Issue by dvdjaco** [mickael-menu/zk#257]
Some automation tools like [mason.nvim](https://github.com/williamboman/mason.nvim) or [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) expect to find linux binaries in the zk "latest release" URL when auto-installing the zk LSP server. These binaries are missing from the last couple of zk releases, which means that some NVim users can't use zk as an LSP server without disabling auto-install and building/installing it manually.

I know this is not a zk bug, but it would help making zk more accessible via zk-nvim, and having Linux binaries would be nice anyway ;-)

I was able to build zk for linux/amd64 using the Docker images from [zk-xcompile](https://github.com/mickael-menu/zk-xcompile). I followed the instructions in the README but I had to change the build command from `./go build` to `go mod tidy && go build`:

`docker run --rm -v "$PWD":/usr/src/zk -w /usr/src/zk mickaelmenu/zk-xcompile:linux-amd64 /bin/bash -c 'go mod tidy && go build'`

**Comment by mickael-menu** [comment]
Yes, unfortunately I was not able to build the Linux binaries for the last release with Docker, I'm not sure why. I don't know much about Docker and haven't used Linux in a decade so any help would be most welcome!

The real command to run is not `./go build` but `make`, as used in the `Makefile`: https://github.com/mickael-menu/zk/blob/c21c4fc21f7fe75f05d3fc3d09e74ffed41ba2ef/Makefile#L35-L36

However it fails with this error from my Macbook M1, for linux-amd64:

```
# runtime/cgo
gcc: error: unrecognized command-line option '-m64'
make: *** [Makefile:3: build] Error 2
```

As a workaround, I wanted to get rid of the `mattn/go-sqlite3` dependency in favor of `zombiezen/go-sqlite`, which would remove the need to compile with Docker. But I didn't have time to finish this yet.

**Comment by dvdjaco** [comment]
Could this be a side effect of the amd64 docker file being tagged as arm64? (See https://github.com/mickael-menu/zk-xcompile/issues/1#top)

I was able to make it work with a locally built amd64 docker image, although I had to add the a line to the `build:` section of the makefile to run `go mod tidy` before `go build`:

```
# Build zk in the current folder.
build:
	go mod tidy
	$(call go,build)
(...)
```

**Comment by mickael-menu** [comment]
I added the missing Linux binaries in the last release. Thank you @dvdjaco for your help in https://github.com/mickael-menu/zk-xcompile/issues/1!

**Comment by dvdjaco** [comment]
Awesome, thank you for your work!
