### ISSUE TITLE
Shell helper not working as intended

### ISSUE THREAD

**Issue by AndOrangutan** [mickael-menu/zk#265]
Greetings, so I was recently trying to redo my notebook setup because I feel that I made some errors in configuring my last one and came across this believed error. 

Based off this previous discussion where you gave me the [initial idea](https://github.com/mickael-menu/zk/discussions/191#discussioncomment-2620501), I would think this syntax should allow me to call this script and pass in the output of `{{dir}}`:

```
{{sh '$HOME/.config/zk/scripts/directory_tagizer.sh {{dir}}'}}
```
but instead it just creates this in a :

```
#{{dir}}
```
Which, based off my script (which I have tested to work based off copied output from a {{dir}}), means it is just passing `{{dir}}` as the input instead of processing it first.

As in that original discussion, I am working to add tags to a note.

**Comment by mickael-menu** [comment]
Sorry there was a misunderstanding. In my original comment, I said that it would be useful if you could pass variables to the `sh` template helper, but it's not supported yet.

However, I think you should be able to use `concat` for this particular example:

```
{{sh (concat '$HOME/.config/zk/scripts/directory_tagizer.sh', dir)}}
```

**Comment by AndOrangutan** [comment]
SWEET! Thank you so much, this perfects my setup :D

To anyone who wants to follow
```
{{sh (concat '<path-to-script> ' dir)}}
```
Script
```
#!/bin/sh

# Grab input
DIR=$1

# Remove file and replace
TRIMREPLACE=$(echo $DIR | sed 's/\// #/g')

if [ -z "$TRIMREPLACE" ]
then
    return
fi

# Add tag
OUTPUT="#$TRIMREPLACE"

echo "$OUTPUT"
```
