### ISSUE TITLE
--link-to  and --linked-by does not work with [[Wikilinks]]

### ISSUE THREAD

**Issue by gour** [mickael-menu/zk#270]
Hello,

`zk` seems very attractive to me...Tried it with the corpus of [10000 markdown files](https://github.com/Zettelkasten-Method/10000-markdown-files) and it does perform well, at least what I could test, while e.g. some Electron-based apps are practically becoming useless with such number of notes.

However, I do not get what I'd expect with a very basic setup...default config file (attached), as well as two small notes (included), testing `--linked-by` and `--link-to`:

```
$ zk list --linked-by havq.md

Found 0 note
$  zk list --linked-by iy3p.md 

Found 0 note
$  zk list --linked-by havq.md 

Found 0 note
$  zk list --link-to havq.md

Found 0 note
```
I use the latest version:

```
$ zk --version
zk 0.11.1
```

What do I miss?

[havq.md](https://github.com/mickael-menu/zk/files/10000551/havq.md)
[iy3p.md](https://github.com/mickael-menu/zk/files/10000553/iy3p.md)
[config.toml.txt](https://github.com/mickael-menu/zk/files/10000569/config.toml.txt)

**Comment by gour** [comment]
After changing the format of YAML front-matter, I was able to resolve the issue. :smile: 

Thank you for `zk`. :wink:

**Comment by mickael-menu** [comment]
I'm glad you found a solution by yourself.

`[[WikiLinks]]` are matching any part of a file's path in the notebook, so `[[havq]]` or `[[iy3p]]` would work, but not using the note title instead.
