### ISSUE TITLE
LSP: Support links with absolute path from notebook root

### ISSUE THREAD

**Issue by k0ral** [mickael-menu/zk#278]
Consider the following notebook structure:
```
notebook_root_folder
 ├──.zk 
 └──some_folder 
    ├──current_file.md 
    └──other_file.md 
```

To link `other_file.md` from within `current_file.md`, it seems that:
1. relative path works: `[Go to other_file](other_file.md)`
2. absolute path from notebook's root does not work: `[Go to other file](/some_folder/other_file.md)`

By "work", I mean that LSP considers the link valid and correctly resolves it when using {Go to definition} action.

Setting `link-format = "[{{title}}]({{path}})"` in `.zk/config.toml` doesn't seem to help: the format is used to generate new links, but not to resolve them.

Did I miss something ? Would it be reasonable for `zk`'s LSP to support (2) ?

**Comment by mickael-menu** [comment]
I'm a bit on the fence for this one. `/some_folder/other_file.md` wouldn't be a valid Markdown href in most cases, for example in a GitHub repository served as GH pages.

**Comment by k0ral** [comment]
> I'm a bit on the fence for this one.

My reasoning was:
- `zk` acknowledges the concept of workspace: by having a root `.zk` folder, also by implementing the Language Server Protocol which defines that concept
- the concept of workspace naturally gives birth to the concept of path relative to that workspace (which I refer to as "absolute path")
- I can't find anything that forbids absolute paths in [Markdown's original specification](https://daringfireball.net/projects/markdown), in fact that specification even includes [an example](https://daringfireball.net/projects/markdown/syntax#link) that _is_ an absolute path
- in the context of HTML-rendered markdown files, if a custom URL prefix is needed, then I would think it is the responsibility of the HTML renderer to handle that ; quoting from the README, `zk` is not "a tool to serve your notes on the web", thus is not the right place to care about URL prefix, right ? :)

I should probably mention [this interesting issue on `mkdocs`](https://github.com/mkdocs/mkdocs/issues/192) that discusses this very topic, and includes arguments from both sides.

> Would you be open to contribute this feature?

Sure, I can certainly try.
