### ISSUE TITLE
ZK_SHELL not being used consistently

### ISSUE THREAD

**Issue by kiil** [mickael-menu/zk#279]
Hi, I am using nushell

nushell does not write redirections in the standard way, so I've set

ZK_SHELL = /usr/bin/sh

this works for the pager (less), but it does not work with the editor command in interactive mode - `zk edit -i`

So when I press ctrl-e, I get:

```
Error: nu::parser::parse_mismatch (link)

  × Parse mismatch during operation.
   ╭─[source:1:1]
 1 │ "/usr/bin/zk" new "/home/lk/GD/TEKST/notebooks/fam" --title '' < /dev/tty > /dev/tty
   ·               ─┬─
   ·                ╰── expected operator
   ╰────
```

Maybe that command should also be run through `sh` when sh is selected as the ZK_SHELL.

**Comment by mickael-menu** [comment]
The command executed when pressing Ctrl-E is ran by `fzf`, not `zk`, so it doesn't take `ZK_SHELL` into account. Try using `SHELL=` instead, which should be taken into account by both `zk` and `fzf`.

**Comment by kiil** [comment]
I see. Thanks for the reply :)
