### ISSUE TITLE
Built macos-x86_64.zip for v0.12.0

### ISSUE THREAD

**Issue by bingocaller** [mickael-menu/zk#282]
Hi @mickael-menu!

First of all, I wanted to thank you for building `zk`; it's awesome! 🙌

Today I ran into a problem very similar to #128, so I took the liberty of building an Intel Mac zip that we might be able to add to Release 0.12.0. I hope you don't mind:

**[zk-v0.12.0-2-g6506198-macos-x86_64.zip](https://github.com/mickael-menu/zk/files/10356604/zk-v0.12.0-2-g6506198-macos-x86_64.zip)**

**Comment by mickael-menu** [comment]
Thank you, I added it to the last release.

Sorry for the trouble, like you said in the issue I don't always have access to an Intel mac. I think it's time I look into automating building the release binaries with GitHub actions.

**Comment by bingocaller** [comment]
Thank you @mickael-menu.

If the GitHub Actions approach doesn't pan out, I'd be happy to assist with Intel builds.
