### ISSUE TITLE
Support aliases for note names

### ISSUE THREAD

**Issue by romariorobby** [mickael-menu/zk#286]
It would be nice to add aliases feature for notes name, for instance:
```yaml
title:  titlename
aliases: aliastotilename, morealias
```

**Comment by mickael-menu** [comment]
What do you have in mind exactly? Aliases are already supported with `--mention` for example.

**Comment by romariorobby** [comment]
> What do you have in mind exactly? Aliases are already supported with `--mention` for example.

Ah right, i didn't notice that. I use zk with neovim. apparently, zk-nvim doesn't show aliases when you searching a note.  I should probably create this pr on zk-nvim repo.
