### ISSUE TITLE
'link-to' to provide line number in format

### ISSUE THREAD

**Issue by huynle** [mickael-menu/zk#289]
First off, thank you for your continual work on this Mickael! It is an amazing tool. No bloat, just what we need, been using it for the last year or so, and its be a joy to customize and work with.

One additional request I would like to check is if were able to get line number result back in the [template-format](https://github.com/mickael-menu/zk/blob/main/docs/template-format.md)

When I do something like `zk list --link-to morzosgc.md --format="{{snippets}}"` i get the snippet of where the link came from. In the case of `linked-by` filtering, we dont need this line number. But when using the `link-to` filtering, it would be useful to get the actual line number where the link is at? this would be nice, because we can feed it into something like a customize `folke/trouble.nvim` vim plugin, or even push it out to a vim quicklist for quick navigation of the back-links in a large file.

I can do some sort of a `grep`, and such, but is there a built in way to do this?

**Comment by mickael-menu** [comment]
Hello, 

I don't have much time for `zk` lately, so it's unlikely that I will implement this any time soon.

However if you want to take a stab at this, I'd be happy to review a pull request.

[The snippet start and end bytes position for each link is stored in the database](https://github.com/mickael-menu/zk/blob/ea4457ad671aa85a6b15747460c6f2c9ad61bf73/internal/core/link.go#L25-L28), from there you could probably derive line and column indexes. The hard stuff would be to extract the information in an efficient way [from the Note DAO](https://github.com/mickael-menu/zk/blob/ea4457ad671aa85a6b15747460c6f2c9ad61bf73/internal/adapter/sqlite/note_dao.go#L437).

Alternatively, if this will be post-processed by another tool, the `zk graph -f json` command prints out the `snippetStart` and `snippetEnd` properties.

**Comment by huynle** [comment]
accidentally closed the issue.. reopening it
