### ISSUE TITLE
group directory not recognized

### ISSUE THREAD

**Issue by mr-majkel** [mickael-menu/zk#291]
Hi,

I have faced an issue (zk v.0.13) with handling of group directory. Group template is not applied unless I pass --group option to `zk new`. The issue is present in Windows 10 and WSL Ubuntu.

Here is my group definition in config.toml:

```
[group.daily]
# Directories listed here will automatically use this group when creating notes.
paths = ["journal/daily"]

[group.daily.note]
# %Y-%m-%d is actually the default format, so you could use {{format-date now}} instead.
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"
```

running `zk new journal/daily --no-input` creates a note with a default template (in the specified directory). If I run `zk new journal/daily --no-input -g daily` a note with the right template is created.

**Comment by mickael-menu** [comment]
I can't reproduce this issue, but I'm testing on macOS. Unfortunately I can't test on Windows or Ubuntu.

If you're able to create a [`tesh` test case](https://github.com/mickael-menu/zk/tree/main/tests) showing the issue in a GitHub action workflow, maybe I can figure it out.
