### ISSUE TITLE
Failed to index the note: no such column: type

### ISSUE THREAD

**Issue by pinpox** [mickael-menu/zk#298]
I can't create new notes and have not been able to find out what is causing this error. The error occurs for `new` and for `edit` commands at least. 

[This](https://github.com/pinpox/nixos/blob/43040c19e2731486235c9ebd9743ddaa8bb3371d/home-manager/modules/zk/config.toml) is my complete zk config.toml.

My zk version is 0.13.0

```
❯ zk new
zk: warning: 2023-03-09-113204.md: failed to index the note: no such column: type
zk: error: new note: 2023-03-09-113503.md: failed to index the note: no such column: typ
```

**Comment by mickael-menu** [comment]
It looks like an issue in a database migration. Can you try deleting the `.zk/notebook.db` file in your notebook and see if that helps? There's nothing that `zk` can't rebuild in the database.
