### ISSUE TITLE
Inconsistency in extra

### ISSUE THREAD

**Issue by kiil** [mickael-menu/zk#312]
If

```
--extra role=zk,prompt="test"
```

```
{{extra.prompt}}
``` 

gives:

```
test
```

If 

```
--extra prompt="test",role=zk
```

```
{{extra.prompt}}
``` 

gives:

```
"test"
```

```
--extra prompt="test",role="zk"
```
gives:

```
test"
```

**Comment by mickael-menu** [comment]
I can't reproduce the issue, I think it might be related to the shell you use.

In any case, you may want to forward this issue to https://github.com/alecthomas/kong, as it is the library used to parse the CLI flags.
