### ISSUE TITLE
Option to change slug separator underscore

### ISSUE THREAD

**Issue by ivan-volnov** [mickael-menu/zk#314]
Hi!

Thanks for the great tool.

Please add an option to change slug separator underscore.

Need a way to make filename `a_new_note.md` instead of `a-new-note.md`

**Comment by mickael-menu** [comment]
Slugs usually use dashes and I'd prefer to keep things simple.

However, you can use this to get the same result in your `.zk/config.toml`:

```toml
filename = "{{#sh 'sed s/-/_/g'}}{{slug title}}{{/sh}}"
```

Which is running `sed "s/-/_/g"` on the slug to substitute the dashes with underscores.
