### ISSUE TITLE
Problem with aliases when option value contains spaces

### ISSUE THREAD

**Issue by kiil** [mickael-menu/zk#316]
This works

```
sh-5.1$ zk new --title "one two"
```

But the following does not:

Config:

```
[alias]
n = "zk new $@"
```

Command and error:

```
sh-5.1$ zk n --title "one two"
zk: error: new note: two: directory not found
```

It seems when using an alias that a value containing spaces, even within quotation marks, is interpreted as separate arguments.

I have this in env:

```
SHELL=/usr/bin/sh
ZK_SHELL=/usr/bin/sh
```

**Comment by kiil** [comment]
This can be solved like so:

```
[alias]
n = 'zk new "$@"'
```

but not sure if that should not be the standard?

**Comment by mickael-menu** [comment]
I think it depends on your shell. I have the same issue with `sh` and `bash` but not with `zsh`.

From what I gather [here](https://stackoverflow.com/a/9995322) and [there](https://stackoverflow.com/a/9994404), it seems expected to wrap `$@` in quotes. As `zk` is forwarding the alias to the shell as if it was run in a shell script, I don't think it should be too smart and auto-wrap `$@`. That might be unexpected and break other use cases.

It could be worth mentioning in the documentation though.

**Comment by kiil** [comment]
That makes sense.
