### ISSUE TITLE
Support links in YAML frontmatter

### ISSUE THREAD

**Issue by bolt12** [mickael-menu/zk#321]
I want to be able to relate notes without it appearing explicitly in the markdown text. To do this I think a design would be to put something like

```yaml
links:
  - [[{{filename}}]]
  - [[{{filename}}]]
```

in the YAML frontmatter

Would this be something that can be done?

**Comment by mickael-menu** [comment]
Depends what you want to use it with. Following frontmatter links with the LSP should already work, I don't think using `--link-to` will though.

**Comment by bolt12** [comment]
Exactly that's the what I'd want to do! Be able to relate multiple notes
without cluttering the content of the notes. I could always make it
explicit, but would be neat to be able to not to and just have that
information for querying purposes

**Comment by mickael-menu** [comment]
I took a quick look, unfortunately it doesn't seem like the Markdown parser I'm using is able to extract the links in the YAML frontmatter. So that would require significant changes.

**Comment by bolt12** [comment]
Thanks for considering my request!

**Comment by alancunha26** [comment]
Maybe this could be achieved similar to what Obsidian is doing?

```yaml
links:
  - "[[file|alias]]"
  - "[alias](link)"
```

I'm migrating to ZK and have a lot of notes with links under the frontmatter, the navigation works as intended, but the `ZkBacklinks` of the nvim plugin don't list this links.

**Comment by tjex** [comment]
Supported with #710
