### ISSUE TITLE
interactive filtering results in `Found 0 note`

### ISSUE THREAD

**Issue by khimaros** [mickael-menu/zk#331]
i traced the issue down to `fzf.parseSelection()`

the call to `stringsutil.SplitLines()` returns an empty array, despite the `output` parameter containing many bytes.

```
2023/06/06 16:23:39 fzf len(output): 153396
2023/06/06 16:23:39 fzf lines: []
Found 0 note
```

## reproduction

when i `zk edit -i -m <name>` it shows up as the top result

when i press enter to select the note, it says `Found 0 note`

the same outcome when using `zk list -i`

this file i'm attempting to open is `153,335` bytes large

## notes

editing the note with `zk edit -m "<name>" -n 1` works fine

editing the note by name `zk edit <name>` works fine

the problem appears to be restricted to fzf integration

**Comment by khimaros** [comment]
i believe the issue will occur with any document larger than `bufio.MaxScanTokenSize` https://pkg.go.dev/bufio#pkg-constants

for files with content beyond this limit, `stringsutil.SplitLines()` never finds the newline after the filename, which means the loop in `fzf.parseSelection()` is never entered.

**Comment by khimaros** [comment]
this patch solves the problem for me.

for files which are larger than 2MB, shows an error to the user. i'm not sure using 2MB for every string split makes sense, but the error checking code at least i think should be incorporated:

```diff
diff --git a/internal/util/strings/strings.go b/internal/util/strings/strings.go
index be5f406..4db54c4 100644
--- a/internal/util/strings/strings.go
+++ b/internal/util/strings/strings.go
@@ -2,6 +2,7 @@ package strings
 
 import (
        "bufio"
+       "log"
        "net/url"
        "regexp"
        "strconv"
@@ -37,9 +38,15 @@ func Pluralize(word string, count int) string {
 func SplitLines(s string) []string {
        var lines []string
        scanner := bufio.NewScanner(strings.NewReader(s))
+       // increase the buffer size to 2Mb
+       buf := []byte{}
+       scanner.Buffer(buf, 2048*1024)
        for scanner.Scan() {
                lines = append(lines, scanner.Text())
        }
+       if err := scanner.Err(); err != nil {
+               log.Fatalf("error while scanning text: %v", err)
+       }
        return lines
 }
```

**Comment by mickael-menu** [comment]
Thanks @khimaros, feel free to open a PR with your patch.
