### ISSUE TITLE
My custom template of link-format doesn't work

### ISSUE THREAD

**Issue by DreamSkanda** [mickael-menu/zk#353]
### Check if applicable

- [X] I have searched the existing issues (**required**)
- [ ] I'm willing to help fix the problem and contribute a pull request

### Describe the bug

When I reference in a note with the custom template, such as [[i5ta]], it shows 'not found'. But I find this worked fine ( showed in #98) before. 

### How to reproduce?

[sample-notebook.zip](https://github.com/mickael-menu/zk/files/13256261/sample-notebook.zip)

1. open the "can-i-reference-correctly.md"
2. see the lsp error

### zk configuration

```toml
[note]
filename = "{{slug title}}"

[format.markdown]
link-format = "[[{{metadata.id}}]]"
```

### Environment

```bash
zk 0.14.0
system: Linux 6.5.9-arch2-1 x86_64 GNU/Linux
```

**Comment by mickael-menu** [comment]
You need to have the ID in the filename of the target note for this to work. Wiki links work with any unique portion of note filenames.

**Comment by DreamSkanda** [comment]
Thank you!
