### ISSUE TITLE
Natural date parsing from a different reference time than now

### ISSUE THREAD

**Issue by kpabijanskas** [mickael-menu/zk#357]
I often find that I need to do natural date parsing from more than just the current time. For example, I need to generate "day before 2020-01-01". But at the moment, calls to `naturaldate.Parse` use `time.Now()` as a reference.

I would like a feature to have a secondary `date` function, maybe in the form of `{{ dateFrom "natural_date" "reference-time-in-rfc3339" }}`. Either that or extend `date` with an optional second parameter for reference time.

I would be very happy to implement this myself and send a pull request if its something you would accept? Maybe you have better ideas for the API?

**Comment by mickael-menu** [comment]
Sure, that would be a useful feature and I would welcome a PR for that.

For the API, I would use a dash `date-from` and maybe put the reference date as the first argument.
