### ISSUE TITLE
zk: error: no such function: REGEXP

### ISSUE THREAD

**Issue by pinpox** [mickael-menu/zk#46]
I've the following directory layout

```
.
├── journal
│  ├── 2021-06-11.md
│  ├── 2021-06-12.md
│  └── 2021-06-13.md
├── note1.md
├── note2.md
├── note3.md

```

Using commands that include the directory name `journal` result in an error though:
List all notes in `./journal`
```
zk list journal
zk: error: no such function: REGEXP
```
List all notes, excluding `./journal`
```
zk list -x journal
zk: error: no such function: REGEXP
```

Not sure if this is a misconfiguration or a bug, could you help me out?

**Comment by mickael-menu** [comment]
Did you build `zk` yourself or use a prebuilt version? It looks like it was compiled on a computer without `libicu`. 

Take a look here: https://github.com/mickael-menu/zk#build-from-scratch

**Comment by pinpox** [comment]
Yes, I did compile it myself. In fact, I'm trying to package the application for NixOS. 
Thanks for the link, I was missing the `icu` tag, it now works!

**Comment by mickael-menu** [comment]
Glad it all worked out!
