### ISSUE TITLE
k: symbol lookup error: zk: undefined symbol: u_foldCase_63

### ISSUE THREAD

**Issue by muralikodali** [mickael-menu/zk#54]
some markdown files are throwing the following error with `zk list`

```
zk: symbol lookup error: zk: undefined symbol: u_foldCase_63
```

**Comment by mickael-menu** [comment]
Could you share:

* Your OS and architecture
* Which version of `zk` you are using, and if it's one of the pre-built binaries from the Releases page
* A minimal Markdown of a note showing the problem

But from the error, it looks like you don't have the same ICU lib on your system that was used to build `zk`. You might need to build `zk` yourself following https://github.com/mickael-menu/zk#build-from-scratch

**Comment by muralikodali** [comment]
My OS is Arch Linux.
I am using latest version of zk ( Version 0.5.0 )

OS info :
```
OS: Arch Linux x86_64
Host: MS-7817 2.0
Kernel: 5.10.45-1-lts
Uptime: 1 min
Packages: 1953 (pacman)
Shell: fish
Resolution: 1920x1080
DE: i3 (X11)
Theme: Nextwaita-2.2 [GTK2/3]
Icons: Paper-Mono-Dark [GTK2/3]
Font:  (pt) [Plasma], SFNS Display 11 (pt) [GTK2/3/4]
Terminal: alacritty
CPU: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz (4) @ 3.5GHz
GPU0: Intel Corporation 4th Generation Core Processor Family Integrated Graphics Controller
Memory: 6519MiB / 7815MiB (83%)
Disk (/): 23GB / 109GB (21%)
Locale: en_US.UTF-8

```
while building from source it throws following error so many times. 
```
bin/bash: warning: shell level (1000) too high, resetting to 1
```
system is hanging up. I have to power off to shut down the computer.

it is also opening browser, showing as follows :  
```
Unable to load page
Error while opening https://github.com/mickael-menu/zk#build-from-scratch
Renderer process was killed (status 9)

Try again
```
markdown file attached for your reference.
[e50e83.md](https://github.com/mickael-menu/zk/files/6720093/e50e83.md)

**Comment by mickael-menu** [comment]
> while building from source it throws following error so many times.
> 
> ```
> bin/bash: warning: shell level (1000) too high, resetting to 1
> ```

That's weird, the script is not calling itself. You can run the `go` command manually with:

```sh
CGO_ENABLED=1 go -tags "fts5 icu" install
```

> it is also opening browser, showing as follows :
> 
> ```
> Unable to load page
> Error while opening https://github.com/mickael-menu/zk#build-from-scratch
> Renderer process was killed (status 9)
> 
> Try again
> ```

I don't understand either what you mean, the build script never open this page (or any page for that matter).

Maybe you want to check here with @nogweii who packaged `zk` for Arch Linux: https://github.com/mickael-menu/zk/discussions/45
 
> markdown file attached for your reference.
> [e50e83.md](https://github.com/mickael-menu/zk/files/6720093/e50e83.md)

Works fine for me.

**Comment by muralikodali** [comment]
Thanks for your reply.

It is the problem with fish shell. I have installed zk from source in zsh shell environment.

But ```zk list``` is producing the following error :  
```
zk: warning: e50e83.md: failed to index the note: database query:
			INSERT INTO notes (path, sortable_path, title, lead, body, raw_content, word_count, metadata, checksum, created, modified)
			VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		: no such module: fts5
```
I have tried to install as you suggested  with ```CGO_ENABLED=1 go -tags "fts5 icu" install```

It outputs  :  
```
flag provided but not defined: -tags
```

**Comment by mickael-menu** [comment]
Make sure you use at least Go 1.16, `-tags` is a valid flag for `go`.

```sh
$ go version
go version go1.16.5 darwin/amd64
```

By the way, I removed the `./go` script and added a real `Makefile` in the latest `main` commit. Won't help with the `-tags` issue though.

**Comment by muralikodali** [comment]
I have installed the latest version of go i.e: 1.16.5
```
go version
go version go1.16.5 linux/amd64
```
but ```CGO_ENABLED=1 go -tags "fts5 icu" install``` producing the same error, as shown above.

I have tried to build zk with aur package. but that build also failed and i have already reported it, on aur platform.

**Comment by mickael-menu** [comment]
Check out `go help build` perhaps? I can see this:

> 	-tags tag,list
		a comma-separated list of build tags to consider satisfied during the
		build. For more information about build tags, see the description of
		build constraints in the documentation for the go/build package.
		(Earlier versions of Go used a space-separated list, and that form
		is deprecated but still recognized.)

**Comment by muralikodali** [comment]
```CGO_ENABLED=1 go install -tags fts5,icu ```  has thrown the following warning, but installation is successful.

```
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3Fts5IndexQuery’:
sqlite3-binding.c:225286:18: warning: ‘memcpy’ specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
225286 |     if( nToken ) memcpy(&buf.p[1], pToken, nTok
```

The compiled binary is installed in the GO root location and indexation of the above file is done without any error.

Thanks for your support.

**Comment by mickael-menu** [comment]
Ha yes, the `-tags` needs to be after the `build` or `install` subcommand, sorry about that.
