### ISSUE TITLE
Use glow for fzf-preview

### ISSUE THREAD

**Issue by mrzv** [mickael-menu/zk#62]
I would like to use [glow](https://github.com/charmbracelet/glow) for `fzf-preview`, but when I try to use it, I just get "Loading" in the preview window, when running `zk list -i`. I'm not sure what the problem is or how to debug it.

**Comment by mickael-menu** [comment]
Are you able to use `glow` as you want using `fzf` directly, bypassing `zk`? Looks like `glow` is an interactive program, I'm not sure this works properly in the `fzf` preview.

If you just want to colorize the output, you could try using [`bat`](https://github.com/sharkdp/bat) instead. This is what I personally use in my `zk` config:

```toml
[tool]
fzf-preview = "bat -p --theme Nord --color always {-1}"
```

**Comment by mrzv** [comment]
I'm not sure how to run `glow` directly under `fzf`; I'm not really familiar with `fzf`. `glow` has an interactive component, but running `glow file.md` renders the file without any interaction, so I was hoping there is a way to get it to work. (Not to mention that with `glow` written in `go`, it seems like it's a natural complement to `zk`.)

I'm a happy user of `bat`, and it works fine as `fzf-preview`, but the output for markdown is not in the same league as `glow` (nor is it trying to be the same).

**Comment by mickael-menu** [comment]
Try this in a folder with Markdown files:

```sh
fzf --preview "glow {1}"
```

Then it's a matter of trial and error to find a set of glow flags that works with `fzf`'s preview.

**Comment by mrzv** [comment]
Ah, that works. And specifying:
```
fzf-preview = "glow {-1}"
```
also works. The only thing missing is color.

**Comment by mrzv** [comment]
I filed charmbracelet/glow#280, so this can be closed.
