### ISSUE TITLE
Allow escaped pipe in wikilink

### ISSUE THREAD

**Issue by chris-sanders** [mickael-menu/zk#68]
When using the Wikilink syntax inside of a markdown table the pipe character has to be escaped to prevent it becoming a new column. Currently the LSP server doesn't seem to allow for the escape character and reports a broken link prevent the use of wikilinks in tables.

| A | B|
|---|---|
| Escaped| [[www.duckduckgo.com\|search engine]]|
| Not Escaped| [[www.duckduckgo.com|search engine]]|

**Comment by mickael-menu** [comment]
That's a bit of an egg-and-chicken situation as `zk` is handling escaped pipes to be able to have a link portion with pipes in it.

Not sure what's the right course of action here... Maybe use regular Markdown links as a workaround?

**Comment by chris-sanders** [comment]
Yup that's what I'm doing, it's perfectly fine and I prefer Markdown links generally. If it's an edge case to deal with it I wouldn't spend a lot of time worrying about this one.

**Comment by mickael-menu** [comment]
Alright, let's close it for now until maybe someone comes up with an idea.
