### ISSUE TITLE
Cyrillic symbols in zk.lsp

### ISSUE THREAD

**Issue by VolkovIlia** [mickael-menu/zk#72]
Found a bug (nvim + zk.lsp)

If you trying to create link using lua vim.lsp.buf.definition command with Cyrillic symbols, it creates ref with ������� blocks.

To reproduce it, write some Cyrillic text - example: русский, visualize it and push `<CR>`.

**Comment by mickael-menu** [comment]
This was caused by a bug in a third-party dependency. You can try it out again from the latest `main` commit.
