### ISSUE TITLE
Notes with broken relative paths are excluded from operations

### ISSUE THREAD

**Issue by chris-sanders** [mickael-menu/zk#78]
I've been rearranging some notes so I can use emanote and zk together and I think I've found a bug in the link validation. I'm moving notes found in a subfolder into the root so I can avoid path mismatches. Notes in the subfolder which references relative paths ex: `[This is a link](../my-note.md)` once moved to the root aren't included in results anymore.

It took me a while to notice because the warning displays after you return from the list command, and is shown on the previous command prompt. Maybe this is intended, but I didn't expect broken links to prevent finding the note, I was intending to first move files and then fix links and was finding that nothing that I moved was 'present' anymore. In fact, it would be super nice if 'invalid link' were a search term that I could look for mistakes and edit them.

**Comment by mickael-menu** [comment]
That's definitely a bug, I think a simple content warning should not prevent the note from being imported.

**Comment by mickael-menu** [comment]
Fixed in `main`, I have a few other things to tackle before the next release.

**Comment by chris-sanders** [comment]
Cool, I've been compiling from source anyway i'll give it a while thanks
for the quick response.

**Comment by chris-sanders** [comment]
Yup just recompiled and tested, all works as expected.
