### ISSUE TITLE
include filename in the index

### ISSUE THREAD

**Issue by pwntester** [mickael-menu/zk#87]
Hi, thanks for this awesome tool!

This may be something stupid Im missing, but when I search for a note (eg: `zk edit --interactive`) I don't get any hits when I search for the filename. For example, if I search for `2021-10-04`, I don't get any hits even though I have a daily note called `2021-10-04.md`. Is there a way to include the filename in the index?

Thanks!

**Comment by mickael-menu** [comment]
Welcome 👋 

This should work already, could you explain a bit more how you do the search? Are you typing the filename in the `fzf` window opened by `zk edit --interactive`? Or using for example `zk list 2021-10-04`?

Also, what's the path of `2021-10-04.md` relative to the root of your notebook?

**Comment by pwntester** [comment]
Hi!

I was doing the search via LSP client and since I missed many notes I tried the CLI tool: `zk edit --interactive` and then typing in the `fzf` prompt. I also tried `zk list 2021-10-04` with no results:

```bash
❯❯❯ pwd
~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Pwntester
❯❯❯ zk index
Indexed 431 notes in 0s
  + 0 added
  ~ 0 modified
  - 0 removed
❯❯❯ zk list 2021-10-04

Found 0 note
```

As you can see, Im moving away from Obsidian, but for some time I will be using the two (Obsidian and Neovim+ZK).

> Also, what's the path of 2021-10-04.md relative to the root of your notebook?

Its `☯️ areas/🗓️ planning/daily notes`

```bash
❯❯❯ ls ☯️\ areas/🗓️\ planning/daily\ notes/2021-10-04.md
☯️ areas/🗓️ planning/daily notes/2021-10-04.md
```

Also, I counted 1000 files in the vault, but only 431 notes are indexed:

```bash
❯❯❯ zk index
Indexed 431 notes in 0s
  + 0 added
  ~ 0 modified
  - 0 removed
❯❯❯ find . -type f -print | wc -l
    1000
```

Is there any debug info I can send you to help you debug this issue?

Thanks!

**Comment by pwntester** [comment]
> You can actually change the format of the fzf line in your zk config, see https://github.com/mickael-menu/zk/blob/main/docs/tool-fzf.md#line-format

That pretty neat, using `{{style "title" path}} {{style "understate" body}}` helps a lot, some paths may be long though, it would be nice to add a `filename` variable to the template  context that only contains the file name

> I'm a bit confused because the LSP client doesn't expose any search interface. Are you using the zk.nvim plugin? It might be an issue in it then, and changing the fzf line in the zk config won't change anything.

Im not using the `zk.nvim` plugin (although I planned to grab some of the telescope menus in the future from it), but just using the built-in LSP client. For autocompletion Im using `nvim-compe` but that should just show the completion candidates returned by zk LSP server. For example, entering `[[zk`, I get the following completion candidates:

![image](https://user-images.githubusercontent.com/125701/136853847-23e1b89a-4318-4b8b-b1a3-8ebf3be2d9dd.png)

Entering `[[2021-10-`, does not return any completion candidates. However, FZF works as expected and shows notes whose filename contains `2021-10-`. Eg (using the above mentioned fzf-line):

![image](https://user-images.githubusercontent.com/125701/136854465-dd9c7868-e92c-4869-89ea-dc04cfdcb523.png)

> Do you have an example (with the content redacted if you want) of a note that is not indexed + its path relative to the root of the notebook?
> Also note that only the note with a .md extension are indexed. You can customize the extension in the config.

Sorry, I was counting all the files (including images), counting only the `.md` files return a much closer count: 
```
┏╸~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Pwntester · ⎇ master ‹✚899…10›
┗╸❯❯❯ find . -name "*.md" -type f -print | wc -l
     448
┏╸~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Pwntester · ⎇ master ‹✚899…10›
┗╸❯❯❯ zk index -f
Indexed 446 notes in 1s
  + 2 added
  ~ 444 modified
  - 2 removed
```

I dont know what are those two files not indexed. Perhaps, adding a `-p` option to `zk index` that return the path of the indexed files, could help debug what two files are missing.

Thanks!

**Comment by pwntester** [comment]
Thanks, no rush, I have my open source projects a bit abandoned lately because of the same reason :)

> I guess they are filtering on the Label instead of the FilterText? As the path is in the FilterText, theoretically you should be able to filter by it.

It was not handling digits correctly: https://github.com/hrsh7th/nvim-cmp/issues/374

**Comment by mickael-menu** [comment]
This last PR should cover the remaining suggestion:

* https://github.com/mickael-menu/zk/pull/103

**Comment by pwntester** [comment]
Awesome, thanks!
