### ISSUE TITLE
Utility command: Generate a new ID

### ISSUE THREAD

**Issue by nogweii** [mickael-menu/zk#93]
I would like a command (and perhaps it's also exposed over LSP?) to generate a new ID following the configuration. My use case is importing old notes from other software / random text files strewn about my system. They don't have an ID and I'd like to add one to them.

For now, duplicating the configuration into a separate script is my solution but I think it would nice to include in `zk` itself.

Something like this? (Assuming you've configured [neuron-compatible IDs](https://github.com/mickael-menu/zk/blob/main/docs/neuron.md))

```sh
$ zk util id
a65c8b45d
```

**Comment by mickael-menu** [comment]
@nogweii It's available in `main`

```shell
$ cat .zk/templates/id.md
{{id}}

$ zk new --dry-run --template id.md 2> /dev/null
ymkh
```

You might need to strip the extra newline that is appended to every generated note to only get the ID.
